# Generated by Django 4.0.3 on 2022-07-18 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='answer_input',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='comment_general',
            field=models.TextField(max_length=524288, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='comment_on_department',
            field=models.TextField(max_length=524288, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='comment_on_department_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='feedback_submission_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='patient_ref',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='question_asked',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='question_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='service_department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
