# Generated by Django 4.0.3 on 2022-07-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_patientfeedback_answer_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfeedback',
            old_name='comment_general',
            new_name='comment_in_general',
        ),
    ]
