# Generated by Django 4.0.3 on 2022-07-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_rename_comment_general_patientfeedback_comment_in_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_SENT_FOR_FEEDBACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uhid', models.CharField(max_length=255, null=True)),
                ('encounter_id', models.CharField(max_length=255, null=True)),
                ('patient_name', models.CharField(max_length=255, null=True)),
                ('patient_contact_number', models.CharField(max_length=255, null=True)),
                ('patient_gender', models.CharField(max_length=255, null=True)),
                ('patient_bed_number', models.CharField(max_length=255, null=True)),
                ('patient_bed_location', models.CharField(max_length=255, null=True)),
                ('patient_admission_date_time', models.DateTimeField(null=True)),
                ('patient_discharge_date_time', models.DateTimeField(null=True)),
                ('sms_sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
