# Generated by Django 4.0.3 on 2022-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_sms_sent_for_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='patient_encounter_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
