# Generated by Django 4.0.3 on 2022-07-21 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_remove_patientfeedback_comment_on_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='feedback_submission_date_time',
            field=models.DateTimeField(),
        ),
    ]
