# Generated by Django 4.0.3 on 2022-07-21 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0007_question_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='email_id',
        ),
        migrations.AddField(
            model_name='alldepartment',
            name='email_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
