# Generated by Django 4.0.3 on 2022-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0008_remove_question_email_id_alldepartment_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='departments_reply',
            field=models.TextField(max_length=524288, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='replied_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='replier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='replier_pr_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
