version: "1.0"

services:
  feedback:
    build:
      context: .
    restart: always
    image: feedback_docker_image
    container_name: feedback_docker_container
    volumes:
      - .:/feedback_and_streamlit
    ports:
      - 8006:8006

  nginx:
    build:
      context: ./nginx
    image: feedback_nginx_docker_image
    container_name: feedback_nginx_docker_container
    restart: always
    ports:
      - 8005:8005
    volumes:
      - ./static:/feedback_and_streamlit/static
