FROM python:3.10.5-alpine3.16
LABEL mainter="Ahmed"


ENV PYTHONUNBUFFERED 1


RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ $DEV = "true" ]; \
    then /py/bin/pip install -r /tmp/requirements.dev.txt ; \
    fi && \
    rm -rf /tmp && \
    adduser \
    --disabled-password \
    --no-create-home \
    ahmed

ENV PATH="/py/bin:$PATH"
