# Generated by Django 4.0.3 on 2022-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uhid', models.CharField(max_length=255, null=True)),
                ('patient_name', models.CharField(max_length=255, null=True)),
                ('patient_contact_number', models.CharField(max_length=255, null=True)),
                ('patient_gender', models.CharField(max_length=255, null=True)),
                ('patient_bed_number', models.CharField(max_length=255, null=True)),
                ('patient_bed_location', models.CharField(max_length=255, null=True)),
                ('patient_admission_date_time', models.DateTimeField(null=True)),
                ('patient_discharge_date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RefDropdownList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_items', models.CharField(max_length=255)),
            ],
        ),
    ]
