# Generated by Django 4.0.3 on 2022-07-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_patientfeedback_patient_encounter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfeedback',
            name='comment_on_department_name',
        ),
    ]
